### ISSUE TITLE
Remove --stable flag

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/barge#157]
Not sure what exactly the stable switch is supposed to mean, stable can only be defined by a certain combination of component versions, not by a branch of one component. Hence, our default versions, manually set at top of `start_ocean.sh` script should be what's considered stable. Just grabbing the `master` branch of any component does in no way guarantee what users see in the end is stable. For whatever reason we have introduced 3 different sets of version combinations: default, "stable" & "latest" and it's not clear to outside users what the difference between default and stable is. 

At the moment, none of those 3 options will bring up something working from end to end, so nothing really is "stable".

Best way would be to remove the confusing stable switch, and change our nomenclatura to:
- default: `./start_ocean.sh`, referring to a manually set combination of releases
- latest: `./start_ocean.sh --latest`, should refer to latest release versions of each component

With that, referring to release versions instead of branches, we could do away with the `master/develop` split-up too, which adds a lot of friction for more agile release processes. So `master` would be always the dev version, and a release is what's considered stable for that component.

**Comment by ttmc** [comment]
I would be okay with removing the `--stable` option. Maybe give an error message for anyone who uses it, telling them just to remove it to get a default working set of versions.

The last suggestion, i.e.

> With that, referring to release versions instead of branches, we could do away with the `master/develop` split-up too, which adds a lot of friction for more agile release processes. So `master` would be always the dev version, and a release is what's considered stable for that component.

would be fine with me (assuming a "release" is just a Git tag on the `master` branch), but should be discussed because it affects many repos and individuals. It's currently documented in the dev-ocean repository (e.g. [here](https://github.com/oceanprotocol/dev-ocean/blob/master/doc/development/branching-model.md) and maybe in some README or release-process documents in other repos?) so I guess that's where it should be suggested. I will open a new issue over there.
